version: '3'
services: 
    fluent:
        image: fluent/fluentd:v1.3-debian-1
        command: -c /fluentd/etc/fluent.conf 
        ports: 
            -   24224:24224
            -   24224:24224/udp
            -   9880:9880
            
        volumes: 
            # -   ./data:/fluentd/log
            -   ./conf:/fluentd/etc
            -   ./data/log:/var/log/test